print("Hello from tomge!")
require("tomge.lazy")
require("tomge.remap")
require("tomge.ui")
require("tomge.whichkey")
require("tomge.oil")
require("tomge.bufferline")
require("tomge.colorizer")
require("tomge.toggleterm")
require("tomge.tabnine")
require("Comment").setup()
