require("tomge.lazy")
require("tomge.remap")
-- require("tomge.plugins.auto_session")
-- require("tomge.plugins.autopairs")
-- require("tomge.plugins.bufferline")
-- require("tomge.plugins.cmp")
-- require("tomge.plugins.colorizer")
-- require("tomge.plugins.conform")
-- require("tomge.plugins.csvview")
-- require("tomge.plugins.dap_python")
-- require("tomge.plugins.fine_cmdline")
-- require("tomge.plugins.gitsigns")
-- require("tomge.plugins.indent_blankline")
-- require("tomge.plugins.lspconfig")
-- require("tomge.plugins.mini")
-- require("tomge.plugins.nvim_surround")
-- require("tomge.plugins.obsidian")
-- require("tomge.plugins.oil")
-- require("tomge.plugins.telescope")
-- require("tomge.plugins.todo_comments")
-- require("tomge.plugins.toggleterm")
-- require("tomge.plugins.tokyonight")
-- require("tomge.plugins.treesitter")
-- require("tomge.plugins.which_key")
require("Comment").setup()
